### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/tidypolars#2]
## Waiting for `r-polars` implementation

- [x] `unite()` (depends on `concat_str()`)
- [x] `slice_sample()` (depends on `sample()` method for DataFrame)
- [x] `separate()` for `LazyFrame` (depends on `unnest()` method)
- [x] fix `pl_colnames()` for `LazyFrame` (need https://github.com/pola-rs/r-polars/issues/243)

## Waiting for `rust-polars` (and therefore `r-polars`) implementation

- [ ] inequality joins -> wait for https://github.com/pola-rs/polars/issues/10068

## Can be done

- pivoting (syntax very close to `data.table::melt()`):
  - [x] wide to long
  - [x] long to wide
- [x] all functions applied on columns can be done **provided that** I find a robust way to reorganize R/tidyverse syntax as polars syntax -> not finished (probably will never be) but I now have a good mechanism for this
- [x] Docs
- [x] checks for LazyFrame

## CI

- [x] more Rversions / OS coverage -> only 4.3 because it's the only one with binaries from R-universe
- [ ] #48

## Future

- [ ] ~find a way to give the original `polars` syntax?~
